"""add preferred market to farms

Revision ID: 78ca4c95950b
Revises: e8e7d97b7056
Create Date: 2026-08-27 18:52:07.917313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ca4c95950b'
down_revision: Union[str, Sequence[str], None] = 'e8e7d97b7056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('preferred_market', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'preferred_market')
    # ### end Alembic commands ###
